language: node_js

branches:
  only:
    - dev

node_js:
  - "13.8"

install:
  - wget -qO- https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz | gunzip > elm
  - chmod +x elm
  - export PATH=$PATH:$(pwd)
  - npm i -g --unsafe elm-test@0.19.1-revision2

script:
  - cd frontend && elm-test
